# Generated by Django 4.2.20 on 2025-05-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
